/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iflytek_cyber_evs_sdk_codec_audio_opus_OpusCodec */

#ifndef _Included_com_iflytek_cyber_evs_sdk_codec_audio_opus_OpusCodec
#define _Included_com_iflytek_cyber_evs_sdk_codec_audio_opus_OpusCodec
#ifdef __cplusplus
extern "C" {
#endif
#undef com_iflytek_cyber_evs_sdk_codec_audio_opus_OpusCodec_CODEC_ENCODE
#define com_iflytek_cyber_evs_sdk_codec_audio_opus_OpusCodec_CODEC_ENCODE 1L
#undef com_iflytek_cyber_evs_sdk_codec_audio_opus_OpusCodec_CODEC_DECODE
#define com_iflytek_cyber_evs_sdk_codec_audio_opus_OpusCodec_CODEC_DECODE 2L
/*
 * Class:     com_iflytek_cyber_evs_sdk_codec_audio_opus_OpusCodec
 * Method:    init_native
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_cyber_evs_sdk_codec_audio_opus_OpusCodec_init_1native
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_iflytek_cyber_evs_sdk_codec_audio_opus_OpusCodec
 * Method:    encode_native
 * Signature: (J[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_cyber_evs_sdk_codec_audio_opus_OpusCodec_encode_1native
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_iflytek_cyber_evs_sdk_codec_audio_opus_OpusCodec
 * Method:    decode_native
 * Signature: (J[BI[BIII)I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_cyber_evs_sdk_codec_audio_opus_OpusCodec_decode_1native
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_iflytek_cyber_evs_sdk_codec_audio_opus_OpusCodec
 * Method:    destroy_native
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_iflytek_cyber_evs_sdk_codec_audio_opus_OpusCodec_destroy_1native
  (JNIEnv *, jobject, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
