package com.iflytek.cyber.iot.show.core.template


object Constant {
    const val PAYLOAD_TYPE = "type"
    const val PAYLOAD_MAIN_TITLE = "main_title"
    const val PAYLOAD_SUB_TITLE = "sub_title"
    const val PAYLOAD_BODY_TEXT = "body_text"
    const val PAYLOAD_BODY_SUB_TEXT = "body_sub_text"
    const val PAYLOAD_BODY_IMAGE_URL = "body_image_url"
    const val PAYLOAD_BACKGROUND_IMAGE_URL = "background_image_url"
    const val PAYLOAD_SKILL_ICON_URL = "skill_icon_url"
    const val PAYLOAD_TEMPLATE_ID = "template_id"
    const val PAYLOAD_LEFT_TEXT = "left_text"
    const val PAYLOAD_LIST_ITEMS = "list_items"
    const val PAYLOAD_RIGHT_TEXT = "right_text"
    const val PAYLOAD_BACK_BUTTON = "back_button"
    const val PAYLOAD_OPTION_ELEMENTS = "option_elements"
    const val PAYLOAD_ELEMENT_ID = "element_id"
    const val PAYLOAD_PRIMARY_TEXT = "primary_text"
    const val PAYLOAD_SECONDARY_TEXT = "secondary_text"
    const val PAYLOAD_TERTIARY_TEXT = "tertiary_text"
    const val PAYLOAD_OPTION_IMAGE_URL = "option_image_url"
    const val PAYLOAD_CURRENT_WEATHER = "current_weather"
    const val PAYLOAD_CONDITION = "condition"
    const val PAYLOAD_DESCRIPTION = "description"
    const val PAYLOAD_LOW_TEMPERATURE = "low_temperature"
    const val PAYLOAD_HIGH_TEMPERATURE = "high_temperature"
    const val PAYLOAD_ICON_URL = "icon_url"
    const val PAYLOAD_WEATHER_FORECAST = "weather_forecast"
    const val PAYLOAD_WEEKDAY = "weekday"
    const val PAYLOAD_DATE = "date"
    const val PAYLOAD_IMAGE_URL = "image_url"

    const val BACK_BUTTON_VISIBLE = "VISIBLE"
    const val BACK_BUTTON_HIDDEN = "HIDDEN"

    const val TYPE_BODY_TEMPLATE_1 = "body_template_1"
    const val TYPE_BODY_TEMPLATE_2 = "body_template_2"
    const val TYPE_BODY_TEMPLATE_3 = "body_template_3"
    const val TYPE_LIST_TEMPLATE_1 = "list_template_1"
    const val TYPE_WEATHER_TEMPLATE = "weather_template"
    const val TYPE_OPTION_TEMPLATE_1 = "option_template_1"
    const val TYPE_OPTION_TEMPLATE_2 = "option_template_2"
    const val TYPE_OPTION_TEMPLATE_3 = "option_template_3"
}
