/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iflytek_ivw_IVWEngine_IVWListener */

#ifndef _Included_com_iflytek_ivw_IVWEngine_IVWListener
#define _Included_com_iflytek_ivw_IVWEngine_IVWListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
